import * as Phaser from "phaser";

// Danh sách phím cố định mà trẻ có thể chọn
export const allowedKeys: { [key: string]: number } = {
  A: Phaser.Input.Keyboard.KeyCodes.A,
  B: Phaser.Input.Keyboard.KeyCodes.B,
  C: Phaser.Input.Keyboard.KeyCodes.C,
  D: Phaser.Input.Keyboard.KeyCodes.D,
  E: Phaser.Input.Keyboard.KeyCodes.E,
  F: Phaser.Input.Keyboard.KeyCodes.F,
  G: Phaser.Input.Keyboard.KeyCodes.G,
  H: Phaser.Input.Keyboard.KeyCodes.H,
  I: Phaser.Input.Keyboard.KeyCodes.I,
  J: Phaser.Input.Keyboard.KeyCodes.J,
  K: Phaser.Input.Keyboard.KeyCodes.K,
  L: Phaser.Input.Keyboard.KeyCodes.L,
  M: Phaser.Input.Keyboard.KeyCodes.M,
  N: Phaser.Input.Keyboard.KeyCodes.N,
  O: Phaser.Input.Keyboard.KeyCodes.O,
  P: Phaser.Input.Keyboard.KeyCodes.P,
  Q: Phaser.Input.Keyboard.KeyCodes.Q,
  R: Phaser.Input.Keyboard.KeyCodes.R,
  S: Phaser.Input.Keyboard.KeyCodes.S,
  T: Phaser.Input.Keyboard.KeyCodes.T,
  U: Phaser.Input.Keyboard.KeyCodes.U,
  V: Phaser.Input.Keyboard.KeyCodes.V,
  W: Phaser.Input.Keyboard.KeyCodes.W,
  X: Phaser.Input.Keyboard.KeyCodes.X,
  Y: Phaser.Input.Keyboard.KeyCodes.Y,
  Z: Phaser.Input.Keyboard.KeyCodes.Z,
  LEFT: Phaser.Input.Keyboard.KeyCodes.LEFT,
  RIGHT: Phaser.Input.Keyboard.KeyCodes.RIGHT,
  UP: Phaser.Input.Keyboard.KeyCodes.UP,
  DOWN: Phaser.Input.Keyboard.KeyCodes.DOWN,
  SPACE: Phaser.Input.Keyboard.KeyCodes.SPACE,
  ENTER: Phaser.Input.Keyboard.KeyCodes.ENTER,
};
